sudo: false

matrix:
    include:
    - os: linux
      language: java
      jdk:  oraclejdk8
      install: true
    - os: linux
      language: java
      jdk:  oraclejdk9
      install: true
    - os: linux
      language: java
      jdk:  oraclejdk10
      install: true
      
 #   - os: osx
 #     language: java
 #     osx_image: xcode9.2
 #     install: true
 #   - os: osx
 #     language: java
 #     osx_image: xcode9.2
 #     install: brew tap caskroom/cask && brew cask info java && brew cask reinstall java

before_script:
  - sh ./gradlew --version
  - sh ./gradlew clean publishToMavenLocal
  - git clone https://github.com/miho/VMF-Runtime
  - cd VMF-Runtime && sh ./gradlew clean publishToMavenLocal
  - cd ..
  - git clone https://github.com/miho/VMF-Tests
  
script:
    - sh ./gradlew clean test
    - cd VMF-Tests && sh ./gradlew clean test
    
