sudo: false

matrix:
    include:
    - os: linux
      language: java
      jdk:  oraclejdk8
      install: true
    - os: linux
      language: java
      jdk:  oraclejdk9
      install: true
    - os: linux
      language: java
      jdk:  oraclejdk10
      install: true
      
 #   - os: osx
 #     language: java
 #     osx_image: xcode9.2
 #     install: true
 #   - os: osx
 #     language: java
 #     osx_image: xcode9.2
 #     install: brew tap caskroom/cask && brew cask info java && brew cask reinstall java

#cache:
#  ccache: true
#  directories:
#   - /Users/travis/build/miho/

#before_script:
  
script:
    - export CWD=$(pwd)
    - cd core
    - sh ./gradlew clean publishToMavenLocal
    - cd $CWD
    - cd runtime
    - sh ./gradlew clean publishToMavenLocal
    - cd $CWD
    - cd gradle-plugin
    - sh ./gradlew clean publishToMavenLocal
    - cd $CWD
    - cd test-suite
    - sh ./gradlew clean test
    - cd $CWD
    
