# Gradle
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  name: ''
  pool: ''
  platform: ''
  jdkVersion: '1.11'
  gradleWrapperFile: 'gradlew.bat'
  workingDirectory: ''
  tasks: 'clean build'



jobs:
- job: 'CORE'
  pool: ${{ parameters.pool }}
  steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'core/gradlew'
        workingDirectory: 'core'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: ${{ parameters.jdkVersion }}
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        tasks: 'clean build publishToMavenLocal'
- job: 'RUNTIME'
  pool: ${{ parameters.pool }}
  steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'runtime/gradlew'
        workingDirectory: 'runtime'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: ${{ parameters.jdkVersion }}
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        tasks: 'clean build publishToMavenLocal'
- job: 'GRADLE-PLUGIN'
  pool: ${{ parameters.pool }}
  steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradle-plugin/gradlew'
        workingDirectory: 'gradle-plugin'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: ${{ parameters.jdkVersion }}
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        tasks: 'clean build publishToMavenLocal'
- job: 'TEST-SUITE'
  pool: ${{ parameters.pool }}
  steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'test-suite/gradlew'
        workingDirectory: 'test-suite'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: ${{ parameters.jdkVersion }}
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        tasks: 'clean test'



#    - task: PublishBuildArtifacts@1
#      inputs:
#        pathToPublish: '$(System.DefaultWorkingDirectory)/build/distributions/${{ parameters.appPackaging }}-${{ parameters.platform }}.zip'


# steps:
# - task: Gradle@2
#   displayName: '[CORE] gradlew clean publish'
#   inputs:
#     gradleWrapperFile: core/gradlew.bat
#     workingDirectory: core
#     tasks: 'clean build publishToMavenLocal'